### PR TITLE
Add empty py-typed file

### LINKED ISSUE #57: Missing py.typed for type checking?
### What happens?

After upgrading from 1.3.2 to 1.4.0, mypy complains whenever we import duckdb.

The error message is of the form:
```
error: Skipping analyzing "duckdb": module is installed, but missing library stubs or py.typed marker [import-untyped]
error: Skipping analyzing "duckdb.typing": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

The `.pyi`files moved from the `duckdb-stubs` folder to `duckdb` itself. [This page](https://typing.python.org/en/latest/spec/distributing.html#packaging-type-information) says:
> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing. This marker applies recursively: if a top-level package includes it, all its sub-packages MUST support type checking as well.

And:
> For stub-only packages adding a py.typed marker is not needed since the name *-stubs is enough to indicate it is a source of typing information.

So is a py.typed file needed now with the new version?

### To Reproduce

```
$ echo "import duckdb" > test.py

# Success with 1.3.2
$ pip install duckdb==1.3.2 > /dev/null && mypy test.py
Success: no issues found in 1 source file

# Error with 1.4.0
$ pip install duckdb==1.4.0 > /dev/null && mypy test.py
test.py:1: error: Skipping analyzing "duckdb": module is installed, but missing library stubs or py.typed marker  [import-untyped]
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)

# Adding py.typed fixes the issue
$ touch $(dirname $(python -c "import duckdb; print(duckdb.__file__)"))/py.typed
$ pip install duckdb==1.4.0 > /dev/null && mypy test.py
Success: no issues found in 1 source file
```

### OS:

OSX

### DuckDB Package Version:

1.3.2 and 1.4.0

### Python Version:

3.13.7

### Full Name:

Gishor Sivanrupan

### Affiliation:

Exaforce

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by gishor**
https://typing.python.org/en/latest/spec/distributing.html#packaging-type-information

> Package maintainers who wish to support type checking of their code
MUST add a marker file named py.typed to their package supporting typing.

Fixes #57

### CODE REVIEW

**Comment by evertlammerts** [comment]
FMI: did you test that this works? I'm a little surprised that the `__init__.pyi` stub isn't picked up and from the docs it isn't clear to me that `py.typed` will ensure that it does get picked up... doesn't it just signal that the package itself supports type hints?

We could also just move the stub back into its own folder for now, if that's what worked before.

**Comment by gishor** [comment]
Yes, I did test it. I ran the same commands as in #57, but I did a `uv build` and `pip install duckdb-python/dist/duckdb-1.4.0.dev213.tar.gz`. I tried it from both `main` and `add-py-typed` branches.

`test.py`:
```
import duckdb
from duckdb.typing import *
```

`main` returns:
```
test.py:1: error: Skipping analyzing "duckdb": module is installed, but missing library stubs or py.typed marker  [import-untyped]
test.py:2: error: Skipping analyzing "duckdb.typing": module is installed, but missing library stubs or py.typed marker  [import-untyped]
test.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 1 file (checked 1 source file)
```

`add-py-typed` returns:
```
Success: no issues found in 1 source file
```

Now I'm not fully sure about the point of `py.typed`. However it is also mentioned in the mypy docs linked in the error message above and here: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages:
> If you would like to publish a library package to a package repository yourself (e.g. on PyPI) for either internal or external use in type checking, packages that supply type information via type comments or annotations in the code should put a py.typed file in their package directory.

This is why I thought it makes sense to add this empty file. I guess a separate folder with only stubs should also work.

**Comment by evertlammerts** [comment]
I'm going to make some fixes related to the stub today as part of #62 #57 and #47 . Closing this in favor of that work.
