### ISSUE TITLE
Mypy error [no-any-return] appears after updating DuckDB from 1.2.2 to 1.4.0

### ISSUE THREAD

**Issue by fjossandon** [duckdb/duckdb-python#80]
### What happens?

I have a Python script that is fully typed and passed `mypy --strict` argument using DuckDB 1.2.2, but several `[no-any-return]` typing errors appeared after updating to DuckDB 1.4.0.

### To Reproduce

Code to reproduce
```
import duckdb
import pandas as pd

duckdb_path = "/path/to/duckdb_typing_test.db"


def duckdb_df(db_path: str)->pd.DataFrame:
    """DuckDB test function."""
    duckdb_conn = duckdb.connect(db_path)
    return duckdb_conn.sql(
        """
        SELECT
            1 AS a,
            2 AS b,
            TRUE as c
        """,
    ).to_df()

print(duckdb_df(duckdb_path))
```
The code works fine, and passes Mypy --strict argument using DuckDB 1.2.2, but starts to fail with DuckDB 1.4.0:
```
$ mypy duckdb_typing.py --strict
Success: no issues found in 1 source file

$ pip install duckdb==1.4.0
Collecting duckdb==1.4.0
  Using cached duckdb-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Using cached duckdb-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (20.4 MB)
Installing collected packages: duckdb
  Attempting uninstall: duckdb
    Found existing installation: duckdb 1.2.2
    Uninstalling duckdb-1.2.2:
      Successfully uninstalled duckdb-1.2.2
Successfully installed duckdb-1.4.0

$ mypy duckdb_typing.py --strict
duckdb_typing.py:10: error: Returning Any from function declared to return "DataFrame"  [no-any-return]
Found 1 error in 1 file (checked 1 source file)

$ mypy -V
mypy 1.18.2 (compiled: yes)
```
Finally, I tried the preview release, but the issue persists:
```
$ pip install duckdb --pre --upgrade
Requirement already satisfied: duckdb in /home/fossandon/pyenvs/base/lib/python3.12/site-packages (1.4.0)
Collecting duckdb
  Downloading duckdb-1.5.0.dev37-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Downloading duckdb-1.5.0.dev37-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (20.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/20.4 MB 1.9 MB/s  0:00:11
Installing collected packages: duckdb
  Attempting uninstall: duckdb
    Found existing installation: duckdb 1.4.0
    Uninstalling duckdb-1.4.0:
      Successfully uninstalled duckdb-1.4.0
Successfully installed duckdb-1.5.0.dev37

$ mypy duckdb_typing.py --strict
duckdb_typing.py:10: error: Returning Any from function declared to return "DataFrame"  [no-any-return]
Found 1 error in 1 file (checked 1 source file)
```
In summary, it looks like the `.to_df()` method was properly typed as returning a Pandas DataFrame object before, but now appears to return Any.

### OS:

Ubuntu 24.04.2 LTS

### DuckDB Package Version:

1.4.0

### Python Version:

3.12.3

### Full Name:

Francisco Ossandon

### Affiliation:

Biome Makers

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration to reproduce the issue?

- [x] Yes, I have

**Comment by evertlammerts** [comment]
Yup, this is a know issue, see #57. We're working on it!

**Comment by fjossandon** [comment]
I see, thanks for the link, I will monitor that other issue instead.
