### PR TITLE
Use offset with length for statement query

### PR DESCRIPTION
**Pull request by smvv**
CI job release [fails](https://github.com/duckdb/duckdb-python/actions/runs/30421972678/job/90480500097#step:7:2680) in `Install sdist` on `main` with:

```c++
In member function ‘std::string duckdb::DuckDBPyStatement::Query() const’: src/pystatement.cpp:32:35:
error: ‘class duckdb::SQLStatement’ has no member named ‘stmt_length’
     32 |         auto &length = statement->stmt_length;
        |                                   ^~~~~~~~~~~
```

### CODE REVIEW

**Comment by evertlammerts** [comment]
Thanks for the fix! There's another breaking change in core's main, so I fixed both in #575. Feel free to commandeer :-)
