### PR TITLE
Adding stubs and making mypy pass

### LINKED ISSUE #57: Missing py.typed for type checking?
### What happens?

After upgrading from 1.3.2 to 1.4.0, mypy complains whenever we import duckdb.

The error message is of the form:
```
error: Skipping analyzing "duckdb": module is installed, but missing library stubs or py.typed marker [import-untyped]
error: Skipping analyzing "duckdb.typing": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

The `.pyi`files moved from the `duckdb-stubs` folder to `duckdb` itself. [This page](https://typing.python.org/en/latest/spec/distributing.html#packaging-type-information) says:
> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing. This marker applies recursively: if a top-level package includes it, all its sub-packages MUST support type checking as well.

And:
> For stub-only packages adding a py.typed marker is not needed since the name *-stubs is enough to indicate it is a source of typing information.

So is a py.typed file needed now with the new version?

### To Reproduce

```
$ echo "import duckdb" > test.py

# Success with 1.3.2
$ pip install duckdb==1.3.2 > /dev/null && mypy test.py
Success: no issues found in 1 source file

# Error with 1.4.0
$ pip install duckdb==1.4.0 > /dev/null && mypy test.py
test.py:1: error: Skipping analyzing "duckdb": module is installed, but missing library stubs or py.typed marker  [import-untyped]
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)

# Adding py.typed fixes the issue
$ touch $(dirname $(python -c "import duckdb; print(duckdb.__file__)"))/py.typed
$ pip install duckdb==1.4.0 > /dev/null && mypy test.py
Success: no issues found in 1 source file
```

### OS:

OSX

### DuckDB Package Version:

1.3.2 and 1.4.0

### Python Version:

3.13.7

### Full Name:

Gishor Sivanrupan

### Affiliation:

Exaforce

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration to reproduce the issue?

- [x] Yes, I have

### PR DESCRIPTION
**Pull request by evertlammerts**
Fixes #57 

- Created and curated new stubs
- Added py.typed
- Added mypy config and made it pass

Still todo:
- Re-enable mypy tests. Through pytest and / or in CI?
- Create a stub validity test?

Adding tests for the validity of stubs would be useful depending on what we can actually test:
- We _can_ test which symbols are exposed. If a function, class, constant etc is added or removed, then the output of a stub generator like pybind11-stubgen reflects that change. We can diff that output against our existing stubs and detect the change.
- We _can_ test changes in types that are automatically discovered by a stub generator, by keeping raw output from the generator in the repo and diffing that against stubgen runs during tests. This might produce false positives of course, when the stub generator changes its behavior.
- Can we test whether changes to the manually curated stubs are valid? Mypy tests can catch mismatches if the changed symbol is used internally, but there's a lot it might miss. This is probably something a reviewer needs to be vigilant about.
- Can we test whether changes to public symbols are reflected in the stubs if it's not a change the stub generator detects? Likely not.

I'm not completely sure yet how much effort the above deserves. I'll definitely add mypy checks and see where we go from there.

### CODE REVIEW

**Comment by evertlammerts** [comment]
@dsevilla can you double check that `from_parquet` and `read_parquet` are up to par now?

**Comment by dsevilla** [comment]
The signatures appear to be correct for both `from_parquet` and `read_parquet`. Two small issues, though:

- The `@pytyping.overload` decorator only appears in the first function of the two overloads. I think it should be included in both.
- The scripts have not been updated with this change of `@pytyping.overload` instead of just `@overload`. I suppose you used other tools, but it would be nice to check that later. Also, I believe the scripts that generate/change the wrapper functions generate correctly the overload for both functions.

Apart from that, correct wrt. these two functions.
